# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
repos:
  - repo: local
    hooks:
      - id: format
        name: tsc
        language: system
        entry: yarn tsc --noEmit
        pass_filenames: false